### ISSUE TITLE
Update Firebase dependencies

### ISSUE THREAD

**Issue by barbeau** [Microsoft/EmbeddedSocial-Android-SDK#113]
**Summary:** 

We're getting this crash in the [`nav` branch](https://github.com/OneBusAway/onebusaway-android/tree/nav) of OBA Android (which targets API 28) for Android versions less than Oreo:

~~~
    java.lang.NoSuchMethodError: No static method zzah()Lcom/google/firebase/iid/zzat; in class Lcom/google/firebase/iid/zzat; or its super classes (declaration of 'com.google.firebase.iid.zzat' appears in /data/app/com.joulespersecond.seattlebusbot-1/split_lib_dependencies_apk.apk:classes2.dex)
        at com.google.firebase.messaging.FirebaseMessagingService.zzb(Unknown Source)
        at com.google.firebase.iid.zzb.onStartCommand(Unknown Source)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3326)
        at android.app.ActivityThread.-wrap21(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1582)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
~~~

https://github.com/OneSignal/OneSignal-Gradle-Plugin/issues/69#issuecomment-428500582 says:

>firebase-iid:17.0.3 was being used which is not compatible with any version of firebase-messaging below 17.3.1.

This matches https://developers.google.com/android/guides/releases#december_13_2018, which says that `firebase-iid:17.0.3 `should not be used, and `17.0.4` should be used instead.

If I run `gradlew onebusaway-android:dependencies` on the command line, I see:

~~~
+--- com.acrowntest.test:sdk:0.7.3
|    +--- com.squareup.picasso:picasso:2.5.2
|    +--- com.fasterxml.jackson.core:jackson-annotations:2.6.2 -> 2.9.4
|    +--- com.google.android.gms:play-services-auth:16.0.1
|    |    +--- com.google.android.gms:play-services-auth-api-phone:16.0.0
|    |    |    +--- com.google.android.gms:play-services-base:16.0.1 (*)
|    |    |    +--- com.google.android.gms:play-services-basement:16.0.1 -> 16.1.0 (*)
|    |    |    \--- com.google.android.gms:play-services-tasks:16.0.1 (*)
|    |    +--- com.google.android.gms:play-services-auth-base:16.0.0
|    |    |    +--- com.google.android.gms:play-services-base:16.0.1 (*)
|    |    |    +--- com.google.android.gms:play-services-basement:16.0.1 -> 16.1.0 (*)
|    |    |    \--- com.google.android.gms:play-services-tasks:16.0.1 (*)
|    |    +--- com.google.android.gms:play-services-base:16.0.1 (*)
|    |    +--- com.google.android.gms:play-services-basement:16.0.1 -> 16.1.0 (*)
|    |    \--- com.google.android.gms:play-services-tasks:16.0.1 (*)
|    +--- com.google.firebase:firebase-core:16.0.1 -> 16.0.6 (*)
|    +--- com.google.firebase:firebase-messaging:17.1.0
|    |    +--- com.google.android.gms:play-services-basement:15.0.1 -> 16.1.0 (*)
|    |    +--- com.google.android.gms:play-services-tasks:15.0.1 -> 16.0.1 (*)
|    |    +--- com.google.firebase:firebase-common:16.0.0 -> 16.0.4 (*)
|    |    +--- com.google.firebase:firebase-iid:[16.2.0] -> 17.0.3 (*)    // firebase-iid:17.0.3 is being introduced here!
|    |    \--- com.google.firebase:firebase-measurement-connector:16.0.0 -> 17.0.1 (*)
~~~ 

As you can see near the bottom (see my comment) `firebase-iid:17.0.3` is being introduced via `com.google.firebase:firebase-messaging:17.1.0`.

Could you bump the following Firebase dependencies to hopefully get rid of this issue?

New dependency versions (latest):
* `firebase-core` to `16.0.6`
*  `firebase-messaging`  to `17.3.4`

**Steps to reproduce:** 

Run [`nav` branch](https://github.com/OneBusAway/onebusaway-android/tree/nav) of OBA Android (which targets SDK 28) for Android versions less than Oreo

**Expected behavior:** 

Don't crash

**Observed behavior:** 

Crash with above stack trace

**Device, Android, and Embedded Social SDK version:** 

~~~
    // Embedded Social SDK
    implementation('com.acrowntest.test:sdk:0.7.3:release@aar') {
        transitive = true
    }
~~~

**Comment by barbeau** [comment]
@acrown-msft Looks like this was addressed in https://github.com/Microsoft/EmbeddedSocial-Android-SDK/pull/111?

**Comment by acrown-msft** [comment]
That is correct

**Comment by barbeau** [comment]
By the way, we tested again with the nav branch and it works fine now!
